In [1]:
print('hai')

hai


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Python310\python.exe -m pip install --upgrade pip' command.


In [4]:
import numpy

In [8]:
a=numpy.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [9]:
s=numpy.array([3,4,5])
print(s)


[3 4 5]


In [10]:
type(s)

numpy.ndarray

In [11]:
a=numpy.array((1,2,3,4))
print(a)

[1 2 3 4]


In [12]:
type(a)

numpy.ndarray

In [13]:
a=numpy.array(4)
print(a)

4


In [19]:
list1=numpy.array([[1,2,3],[4,5,6]])
print(list1)

[[1 2 3]
 [4 5 6]]


In [20]:
list2=numpy.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(list2)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [29]:
list3=numpy.array([[[1,2,3], [4,5,6]],[[1,2,3],[4,5,6]]])
print(list3.ndim)


3


In [30]:
import numpy as np

In [39]:
list=np.array([1,2,3],ndmin=5)
print(list)

[[[[1 2 3]]]]


In [43]:
l=np.array([1,2,3,4])

print(l[2]+l[3])

7


In [84]:
lis=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(lis[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [68]:
list4=np.array([1,2,3,4,5,6,7])
print(list4[::2])

[1 3 5 7]


In [100]:
import numpy as np
arr=np.array([1,2,3,4,5,6],dtype='S')
print(arr)
print(arr.dtype)
 
               
               

[b'1' b'2' b'3' b'4' b'5' b'6']
|S1


In [105]:
arr1=np.array([1,1,0,2])
#convert floating point no into int
b=arr1.astype('i')
b=arr1.astype('bool')
print(b)

[ True  True False  True]


In [110]:
#rows and columns
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2.shape)

(2, 4)


In [115]:
arr3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=arr3.reshape(4,3)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [116]:
arr4=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
n=arr4.reshape(2,3,2)
print(n)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [118]:
arr5=np.array([1,2,3,4])
arr6=np.array([5,6,7,8])
c=np.concatenate((arr5,arr6))
print(c)




[1 2 3 4 5 6 7 8]


In [136]:
arr7=np.array([[1,2,3,4],[5,6,7,8]])
arr8=np.array([[3,4,5,6],[7,8,8,9]])
c=np.dstack((arr7,arr8))
#c=np.vstack((arr7,arr8))
#=np.hstack((arr7,arr8))
print(c)



[[[1 3]
  [2 4]
  [3 5]
  [4 6]]

 [[5 7]
  [6 8]
  [7 8]
  [8 9]]]


In [139]:
arr9=np.array([1,2,3,4,5,6,7,8,9])
b=np.array_split(arr9,3)
print(b)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [37]:
#no.of matrix,r&c
v=np.ones((1,3,2))
print(v)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [54]:
li=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(li[1,1,1])

11


In [1]:
import numpy as np

In [9]:
#st,sp,equally div
a=np.linspace(1,31,6)
print(a)

[ 1.  7. 13. 19. 25. 31.]


In [19]:
a=np.full((4,4),12)
print(a)
d=np.full((3,3),5)
print(d)

[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [23]:
#start,stop,no.of elements
r=np.random.randint(0,10,5)
print(r)

[9 7 0 1 6]


In [30]:
# start,stop,rows&cols
r1=np.random.randint(20,50,(3,3))
print(r1)
r2=np.random.randint(10,30,(7,7))
print(r2)

[[25 23 33]
 [35 49 30]
 [24 39 27]]
[[21 25 23 10 14 22 16]
 [24 17 14 19 26 22 24]
 [17 17 21 21 28 12 24]
 [17 15 20 29 13 26 16]
 [28 13 23 26 20 11 20]
 [24 25 20 28 12 19 14]
 [22 24 20 27 29 12 21]]


In [35]:
#4 rows & 6 cols
n1=np.random.random((4,6))
print(n1)

[[0.87612747 0.91693009 0.46202805 0.54008484 0.43836255 0.31736722]
 [0.69692007 0.56804042 0.05843553 0.78423583 0.46615253 0.31444289]
 [0.0108277  0.94906459 0.62385738 0.79623412 0.01546722 0.61590825]
 [0.64556843 0.55271316 0.08636343 0.02387942 0.76204214 0.72508828]]


In [5]:
a=np.arange(10,20,0.5)
print(a)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5]
